package simulation.generator;

//

import java.util.ArrayList;
import simulation.data.FieldOfVision;
import simulation.data.Vehicle;
import simulation.road.Road;
import simulation.road.RoadWay;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FieldOfVisionGenerator.java
//  @ Date : 28/04/2013
//  @ Author : 
//
//




public class FieldOfVisionGenerator {
    
    public static FieldOfVision generateFieldOfVision(Vehicle vehicle, FieldOfVision fieldOfVision){
        RoadWay roadWay;
        roadWay = vehicle.getVehiclePosition().getRoadWay();
        Road road;
        road = roadWay.getRoad();
        
        
        
        return null;
    }
}
